#!/usr/bin/env bash
set -euo pipefail
INPUT_TEXT="$@"

if [[ -z "$INPUT_TEXT" ]]; then
    # Check if there's only one executable
    if [[ -z "$INPUT_TEXT" ]]; then
        INPUT_TEXT=$(find . -maxdepth 5 -executable -type f -printf "%f\n")
        if [[ $(echo "$INPUT_TEXT" | wc -l) -ne 1 ]]; then
            echo "No input given and couldn't find a single executable in the current directory."
            exit 1
        fi
    fi
fi

INPUT_TEXT="-Mintel $INPUT_TEXT"

if [[ ! "$INPUT_TEXT" =~ "-d" ]]; then
    if [[ ! "$INPUT_TEXT" =~ "-D" ]]; then
        # Disassemble only .text by default
        INPUT_TEXT="-d $INPUT_TEXT"
    fi
fi


# Escape for `less` prompt (it usually wouldn't display dots)
INPUT_ESCAPED="${INPUT_TEXT//./\\.}"

objdump $INPUT_TEXT | less --prompt="Output of objdump $INPUT_ESCAPED"
